### ISSUE TITLE
Code is not working for different cronology in labels

### ISSUE THREAD

**Issue by monjoybme** [Jingnan-Jia/segmentation_metrics#20]
Hi,
This algorithm works well if both the manual and automated segmentation files have the same labels for each segment. That means "segment_1" of manual segmentation should match the "segment_1" of automated segmentation. Similarly, "segment_2" of manual segmentation should match the "segment_2" of automated segmentation. This code is not working if manual and automated segmentation has different label values. In my case, "segment_1" of automated segmentation matches "segment_4" of manual segmentation. Similarly, “Segment_2” of the automated segmented file matches with “Segment_3” of the manual segmented file. Is there any way to fix this issue?

**Comment by Jingnan-Jia** [comment]
Hi @monjoybme , do you mean the figure bellow?
![image](https://user-images.githubusercontent.com/34941987/236278327-0c8e12ee-689e-461b-ac4e-bacbbeb59d17.png)

If yes, I advice you at first do some preprocessing so that the labels between automated segmentations and manual segmentations are the same for the same objects. 

For instance, 

```
# exchange the label_1 and label_4 for the numpy array `auto_seg`
auto_seg[auto_seg==4]==999
auto_seg[auto_seg==1]==4
auto_seg[auto_seg==999]==1

```

**Comment by monjoybme** [comment]
@Jingnan-Jia Yes, correct. Can you share full code?

**Comment by monjoybme** [comment]
Solved this problem. Happy to create a pull request if you are interested.
