### ISSUE TITLE
Check msd computation

### ISSUE THREAD

**Issue by jhlegarreta** [Jingnan-Jia/segmentation_metrics#31]
@Jingnan-Jia If `msd` is the mean (Average) surface distance, shouldn't it provide the exact same result as the `assd` value in `medpy`?

```
metrics = sg.write_metrics(
    labels=labels,
    gdth_img=gdth_np,
    pred_img=pred_np,
    spacing=spacing,
  )[0]

# Using a slighlty modified version of medpy.metric.binary.assd as their implementation fails for arrays not having the same dimensionality
assd = np.mean(
    np.hstack(
        [
            medpy.metric.binary.__surface_distances(pred_np, gdth_np, voxelspacing=spacing, connectivity=1),
            medpy.metric.binary.__surface_distances(gdth_np, pred_np, voxelspacing=spacing, connectivity=1),
        ]
    )
)

assert np.allclose(metrics[0]["msd"], assd)
```

It turns out that they do not match, so there is something in the definitions that may need to be checked. And despite e.g. HD provides the same result, the definitions that you use seem to differ, and may need to be checked against the canonical definitions of these metrics.

**Comment by Jingnan-Jia** [comment]
@jhlegarreta Thank you for pointing it out. We will check soon.

**Comment by Jingnan-Jia** [comment]
@jhlegarreta Can you tell me the version of medpy you used? Because I cannot reproduce your results. Previously it was indeed some issue like what you mentioned. And I proposed the issue (https://github.com/loli/medpy/issues/108) to Medpy and Medpy developers found that their code has some problems. Then they fixed their bug. Therefore, I am not sure if this is because that you still used the old Medpy package? Can you check it ? And then upgrade your Medpy and our seg-metrics to see if the same issue still exists?

**Comment by jhlegarreta** [comment]
I know I have been lagging behind this @Jingnan-Jia; I still have it in my ToDo list. I will come back when time permits.
